movie/movie/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('movies/', include('movies.urls',namespace='movies'),),
]

movie/movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'movies'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logined/(\d+)/$',views.logined,name='logined'),
    url(r'^register/$',views.register,name='register'),
    url(r'^usericted/(\d+)/$',views.collected,name='collected'),
    url(r'^addconfo/(\d+)/$',views.userinfo,name='userinfo'),
    url(r'^collellect/(\d+)/$',views.addcollect,name='addcollect'),
    url(r'^delcollect/(\d+)/$',views.delcollect,name='delcollect'),
    url(r'^edituser/(\d+)/$',views.edituser,name='edituser'),
    url(r'^logout/$',views.logout,name='logout'),
]

movie/movies/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.

class MyUser(User):
    uicon = models.ImageField(upload_to='%Y/%m/%d/icons',null=True,blank=True)

class Movies(models.Model):
    title = models.CharField(max_length=50,unique=True)
    image = models.CharField(max_length=200)
    duration = models.IntegerField(default=0)
    class Meta():
        verbose_name = '电影'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.title

class Collections(models.Model):
    mid = models.ForeignKey(Movies,on_delete=models.CASCADE,null=True,unique=True)
    uid = models.ForeignKey(MyUser,on_delete=models.CASCADE,null=True)
    class Meta():
        verbose_name = '收藏'
        verbose_name_plural = verbose_name

movie/movies/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.contrib.auth.models import User
import datetime
from datetime import timedelta
from django.core.mail import send_mail,send_mass_mail
from django.conf import settings
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer,BadSignature,SignatureExpired
from django.views.decorators.cache import cache_page
from PIL import Image,ImageDraw,ImageFont
import random,io
from .models import MyUser,Collections,Movies
from .views_constant import HTTP_OK, HTTP_USER_EXIST
import requests
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views here.

def index(request):
    allmovies = get_movies_image('https://www.vmovier.com/apiv3/index/getBanner')
    allimages = []
    for movie in allmovies:
        image = movie.get('image')
        images = str(image)
        allimages.append(images)

    movies = get_movies('https://www.vmovier.com/apiv3/post/getPostInCate?cateid=0&p=1')

    try:
        for movie in movies:
            movies = Movies()
            title = movie.get('title')
            movies.title = title

            ima = movie.get('image')
            movies.image = ima

            duration = movie.get('duration')
            movies.duration = duration
            movies.save()
    except Exception as e:
        amovies = Movies.objects.all()
        p = Paginator(amovies, 3)
        page = request.GET.get('page')
        try:
            amovie = p.page(page)
        except PageNotAnInteger:
            amovie = p.page(1)
        except EmptyPage:
            amovie = p.page(p.num_pages)
        return render(request,'movies/index.html',locals())
    amovies = Movies.objects.all()
    return render(request,'movies/index.html',locals())

def login(request):
    if request.method == 'GET':
        return render(request,'movies/login.html')
    elif request.method == 'POST':
        name = request.POST.get('username')
        pwd = request.POST.get('password')
        user = MyUser.objects.filter(username=name).first()
        if user:
            password = user.password
            if pwd == password:
                request.session['username'] = name
                all_movies = get_movies_image('https://www.vmovier.com/apiv3/index/getBanner')
                all_images = []
                for movie in all_movies:
                    image = movie.get('image')
                    images = str(image)
                    all_images.append(images)
                # 获取全部电影
                a_movies = Movies.objects.all().order_by('-id')
                icons_url = "/static/upload/" + user.uicon.url
                user = user
                p = Paginator(a_movies, 3)
                page = request.GET.get('page')
                try:
                    amovie = p.page(page)
                except PageNotAnInteger:
                    amovie = p.page(1)
                except EmptyPage:
                    amovie = p.page(p.num_pages)
                return render(request,'movies/logined.html',locals())
            else:
                error = '密码错误'
                return render(request,'movies/login.html',locals())
        else:
            error = '用户不存在'
            return render(request, 'movies/login.html', locals())
    return render(request,'movies/login.html')

def register(request):
    if request.method == 'GET':
        return render(request,'movies/register.html')
    elif request.method == 'POST':
        name = request.POST.get('username')
        pwd = request.POST.get('password')
        spwd = request.POST.get('s_password')
        email = request.POST.get('email')
        icon = request.FILES.get('icon')
        if pwd != spwd:
            error = '两次密码输入不一致'
            return render(request,'movies/register.html',locals())
        else:
            try:
                user = MyUser()
                user.username = name
                user.password = pwd
                user.email = email
                user.uicon = icon
                user.save()
            except Exception:
                return render(request,'movies/register.html')
        return render(request,'movies/login.html')

def collected(request,id):
    all_movies = get_movies_image('https://www.vmovier.com/apiv3/index/getBanner')
    all_images = []
    for movie in all_movies:
        image = movie.get('image')
        images = str(image)
        all_images.append(images)
    user = MyUser.objects.get(pk=id)
    name = user.username
    y_icons_url = "/static/upload/" + user.uicon.url
    collections = Collections.objects.filter(uid=id)
    return render(request,'movies/collected.html',locals())

def addcollect(request,id):
    movie = Movies.objects.get(pk=id)
    user = MyUser.objects.get(username=request.session.get('username'))
    try:
        Collections.objects.get(mid=movie)
        return redirect(reverse('movies:collected', args=str(user.id)))
    except:
        try:
            collection = Collections()
            collection.mid = movie
            collection.uid = user
            collection.save()
        except Exception:
            return HttpResponse('收藏失败')
        return redirect(reverse('movies:collected',args=str(user.id)))

def delcollect(request,id):
    try:
        movie = Movies.objects.get(pk=id)
        del_movie = Collections.objects.get(mid=movie)
        del_movie.delete()
        user = MyUser.objects.get(username=request.session.get('username'))
        return redirect(reverse('movies:collected',args=str(user.id)))
    except Exception:
        return HttpResponse('删除失败')

def userinfo(request,id):
    user = MyUser.objects.get(pk=id)
    icons_url = "/static/upload/" + user.uicon.url
    email = user.email
    name = user.username
    return render(request, 'movies/userinfo.html',locals())

def edituser(request,id):
    user = MyUser.objects.get(pk=id)
    a_movies = Movies.objects.all()
    all_movies = get_movies_image('https://www.vmovier.com/apiv3/index/getBanner')
    all_images = []
    for movie in all_movies:
        image = movie.get('image')
        images = str(image)
        all_images.append(images)
    if request.method == 'GET':
        return render(request, 'movies/userinfo.html',locals())
    else:
        email = request.POST['email']
        icon = request.FILES['uicon']
        user.email = email
        user.uicon = icon
        user.save()
        icons_url = "/static/upload/" + user.uicon.url
        return redirect(reverse('movies:logined',args=str(id)))

def logout(request):
    del request.session['username']
    return redirect(reverse('movies:index'))

def logined(request,id):
    user = MyUser.objects.get(pk=id)
    all_movies = get_movies_image('https://www.vmovier.com/apiv3/index/getBanner')
    all_images = []
    for movie in all_movies:
        image = movie.get('image')
        images = str(image)
        all_images.append(images)
    icons_url = "/static/upload/" + user.uicon.url
    a_movies = Movies.objects.all().order_by('-id')
    p = Paginator(a_movies, 3)
    page = request.GET.get('page')
    try:
        amovie = p.page(page)
    except PageNotAnInteger:
        amovie = p.page(1)
    except EmptyPage:
        amovie = p.page(p.num_pages)
    return render(request,'movies/logined.html',locals())

def get_movies_image(url):

    resp = requests.get(url)

    # print(resp.status_code)

    result = resp.json()

    movies = result.get("data")

    # print(movies)

    return movies

def get_movies(url):

    resp = requests.get(url)

    # print(resp.status_code)

    result = resp.json()

    movies = result.get("data")

    return movies

movie/templates/movies/collected.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/js/jquery.js"></script>
		<script type="text/javascript" src="/static/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/swiper.css" />
		<script type="text/javascript" src="/static/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/css/reset.css" />

		<link rel="stylesheet" type="text/css" href="/static/css/home.css"/>
		<script type="text/javascript" src="/static/js/home.js" ></script>

        <script TYPE="text/javascript" src="/static/collect/collect.js"></script>

	</head>

	<body>

		<div class="container-fluid">

			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Rock</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<!--<li>
							<a href="#">注册</a>
						</li>
						<li>
							<a href="#">登陆</a>
						</li>-->
						<li>
							<a class="icon" href="#">
								<img width="40" height="40" class="img-circle" alt="" src={{ y_icons_url }} />
							</a>
						</li>

						<li>
							<a href=""><span>{{ name }}</span></a>
						</li>
					</ul>
				</div>

			</nav>

		<div class="swiper-container">
				<div class="swiper-wrapper">
                    {% for image in all_images %}
                        <div class="swiper-slide">
						<img src='{{ image }}' alt="">
					    </div>
                    {% endfor %}
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination swiper-pagination-white"></div>
				<!-- Add Arrows -->
				<div class="swiper-button-next swiper-button-white"></div>
				<div class="swiper-button-prev swiper-button-white"></div>
			</div>

			<ul class="nav nav-tabs child-nav">
				<li role="presentation" >
					<a href="{% url "movies:logined" user.id %}">最新推荐</a>
				</li>
				<li role="presentation" class="active">
					<a href="#">收藏</a>
				</li>

			</ul>


			<ul class="movie_list">
                {% for collection in collections %}


				<li>
					<div class="movie_list_left">
						<a target="_blank" href="#" title="{{ collection.mid.title }}">
							<img src="{{ collection.mid.image }}" alt="{{ collection.mid.title }}">
							<div class="bottom-cover">
								<span class="film-time">{{ collection.mid.duration }}</span>
							</div>
						</a>
					</div>

					<div class="movie_list_right">
						<h2>
							<a target="_blank" href="" title="{{ collection.mid.title }}">
								<span>{{ collection.mid.title }}</span>
							</a>
						</h2>

						<div class="movie-intro">
							{{ collection.mid.title }}
						</div>
						<div class="movie-like">
                            <a href="{% url 'movies:delcollect' collection.mid.id %}" ><span id="movie_like" class="glyphicon glyphicon-heart" style="color: red" ></span></a>
							<span></span>
						</div>
					</div>
				</li>
                {% endfor %}




			</ul>

		</div>

	</body>

</html>

movie/templates/movies/index.html
<!DOCTYPE html>
<html>
{% load static%}
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/js/jquery.js"></script>
		<script type="text/javascript" src="/static/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/swiper.css" />
		<script type="text/javascript" src="/static/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/css/reset.css" />

		<link rel="stylesheet" type="text/css" href="/static/css/home.css"/>
		<script type="text/javascript" src="/static/js/home.js" ></script>
        <style>
            .img{
                width: 90%;
                margin-top: 10px;
            }
        </style>
	</head>

	<body style="background-color: #F1F1F1">
    {% csrf_token %}

		<div class="container-fluid">

			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Sunck</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="{% url 'movies:register' %}">注册</a>
						</li>
						<li>
							<a href="{% url 'movies:login' %}">登陆</a>
						</li>
						<!--<li>
							<a class="icon" href="#">
								<img width="40" height="40" class="img-circle" alt="" src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" />
							</a>
						</li>

						<li>
							<a href=""><span>Username</span></a>
						</li>-->
					</ul>
				</div>

			</nav>

			<div class="swiper-container">
				<div class="swiper-wrapper">
                    {% for image in allimages %}
                        <div class="swiper-slide">
						<img src='{{ image }}' alt="">
					    </div>
                    {% endfor %}
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination swiper-pagination-white"></div>
				<!-- Add Arrows -->
				<div class="swiper-button-next swiper-button-white"></div>
				<div class="swiper-button-prev swiper-button-white"></div>
			</div>

			<ul class="nav nav-tabs child-nav">
				<li role="presentation" class="active">
					<a href="#">最新推荐</a>
				</li>
{#				<li role="presentation">#}
{#					<a href="#">收藏</a>#}


			</ul>


			<div class="movie" style="background-color:#ffffff;width: 44%;margin-left: 20%;border: #E5E5E5 solid 2px;float: left">
                <ul class="movie_list" style="width: 90%" >
                    {% for movie in amovie %}
                    <li>
                        <div class="movie_list_left" style="width: 40%">
                            <a target="_blank" href="#" title="{{ movie.title }}">
                                <img src="{{ movie.image }}" alt="{{ movie.title }}">
                                <div class="bottom-cover">
                                    <span class="film-time">{{ movie.duration }}</span>
                                </div>
                            </a>
                        </div>

                        <div class="movie_list_right" style="width: 60%">
                            <h2>
                                <a target="_blank" href="" title="{{ movie.title }}">
                                    <span>{{ movie.title }}</span>
                                </a>
                            </h2>

                            <div class="movie-intro">
                                {{ movie.title }}
                            </div>
                            <div class="movie-like">
                                <a href="#"><span class="glyphicon glyphicon-heart" ></span></a>
                                <span></span>
                            </div>
                        </div>
                    </li>
                    {% empty %}
                        没有电影
                    {% endfor %}
                    <li>
                        <div class="movie_list_left" style="width: 40%">
                            <a target="_blank" href="#" title="超酷一镜到底创意倒放MV《串烧2017》">
                                <img src="https://cs.vmovier.com/Uploads/cover/2017-12-21/5a3b7c046a1d5_cut.jpeg@600w_400h_1e_1c.jpg" alt="超酷一镜到底创意倒放MV《串烧2017》">
                                <div class="bottom-cover">
                                    <span class="film-time">02:48</span>
                                </div>
                            </a>
                        </div>

                        <div class="movie_list_right" style="width: 60%">
                            <h2>
                                <a target="_blank" href="" title="超酷一镜到底创意倒放MV《串烧2017》">
                                    <span>超酷一镜到底创意倒放MV《串烧2017》</span>
                                </a>
                            </h2>

                            <div class="movie-intro">
                                在这个倒叙的世界里，唯有一个人与众不同
                            </div>
                            <div class="movie-like">
                                <span class="glyphicon glyphicon-heart" style="color: red;"></span>
                                <span>199</span>
                            </div>
                        </div>
                    </li>


                </ul>
                <div class="pagination" style="width: 13%">
                    <ul>
                        {% if amovie.has_previous %}
                            <a href="?page={{ amovie.previous_page_number }}">上一页</a>
                        {% endif %}
                            <li></li>
                        <span class="current">第 {{ amovie.number }} 页 / 共 {{ amovie.paginator.num_pages }} 页</span>
                        {% if amovie.has_next %}
                            <a href="?page={{ amovie.next_page_number }}">下一页</a>
                        {% endif %}
                    </ul>
                </div>

            </div>
            <img src="/static/img/5.png" alt="" style="width: 14%;margin-left: 2%">
            <div style="background-color:#ffffff;width: 14%;margin-right: 20%;border: #E5E5E5 solid 2px;float: right;text-align: center;">
                <span style="font-size: 16px;border-left: 4px solid #2689ff;color: #393939;float: left;padding: 5px 0px 5px 18px;margin:10px 0">热门活动</span>
                <ul>
                    <li><img class="img" src="/static/img/1.jpg" alt=""></li>
                    <li><img class="img" src="/static/img/2.jpg" alt=""></li>
                    <li><img class="img" src="/static/img/3.jpg" alt=""></li>
                    <li><img class="img" src="/static/img/4.jpg" alt=""></li>
                    <li><img class="img" src="/static/img/1.jpg" alt=""></li>
                </ul>
            </div>

		</div>

	</body>

</html>

movie/templates/movies/login.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/js/jquery.js"></script>
		<script type="text/javascript" src="/static/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.css" />

		<link rel="stylesheet" type="text/css" href="/static/css/swiper.css" />
		<script type="text/javascript" src="/static/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/css/reset.css" />
		<style type="text/css">
			.form-info {
				border: 1px solid orange;
				margin: 100px auto;
				width: 30%;
				padding: 50px;
			}
			
			.form-info h2 {
				font-size: 2rem;
				margin-bottom: 20px;
			}
			
			.form-info .submit {
				text-align: center;
			}
            .error{
                border: #b92c28 1px solid;
                color: #b92c28;
            }
		</style>
	</head>

	<body>

		<div class="container-fluid">
			<div class="form-info">

				<h2>用户登陆</h2>
                {% if error %}
                    <div class="error">
                        <strong>Error:</strong>{{ error }}
                    </div>
                {% endif %}

				<form action="{% url 'movies:login' %}" method="post">
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" class="form-control" name="username" id="exampleInputEmail1" placeholder="请输入用户名">
						<p class="help-block">请输入6-16位用户名</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">密码</label>
						<input type="password" class="form-control" name="password" placeholder="请输入密码">
						<p class="help-block">请输入6位以上拼音字母组合密码</p>
					</div>

					<div class="submit"><button type="submit" class="btn btn-primary">登陆</button></div>

				</form>
			</div>
		</div>

	</body>

</html>

movie/templates/movies/logined.html
<!DOCTYPE html>
<html>

	<head>
        {% load static %}

		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/js/jquery.js"></script>
		<script type="text/javascript" src="/static/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/swiper.css" />
		<script type="text/javascript" src="/static/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/css/reset.css" />

		<link rel="stylesheet" type="text/css" href="/static/css/home.css"/>
		<script type="text/javascript" src="/static/js/home.js" ></script>
        <script type="text/javascript" src="/static/collect/collect.js"></script>
        <style>
            .img{
                width: 90%;
                margin-top: 10px;
            }
        </style>
	</head>

	<body style="background-color: #F1F1F1">

		<div class="container-fluid">

			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Sunck</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<!--<li>
							<a href="#">注册</a>
						</li>
						<li>
							<a href="#">登陆</a>
						</li>-->
						<li>
							<a class="icon" href="#">
								<img width="40" height="40" class="img-circle" alt="" src={{ icons_url }} />
							</a>
						</li>

						<li>
							<a href="{% url 'movies:userinfo' user.id %}"> <span>{{ user.username }}</span></a>
						</li>
                        <li>
                            <a href="{% url 'movies:logout' %}">退出</a>
                        </li>
					</ul>
				</div>

			</nav>

			<div class="swiper-container">
				<div class="swiper-wrapper">
                    {% for image in all_images %}
                        <div class="swiper-slide">
						<img src='{{ image }}' alt="">
					    </div>
                    {% endfor %}
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination swiper-pagination-white"></div>
				<!-- Add Arrows -->
				<div class="swiper-button-next swiper-button-white"></div>
				<div class="swiper-button-prev swiper-button-white"></div>
			</div>

			<ul class="nav nav-tabs child-nav">
				<li role="presentation" class="active">
					<a href="#">最新推荐</a>
				</li>
				<li role="presentation">
					<a href="{% url 'movies:collected' user.id%}">收藏</a>
				</li>

			</ul>


			<div class="movie" style="background-color:#ffffff;width: 44%;margin-left: 20%;border: #E5E5E5 solid 2px;float: left">
                <ul class="movie_list" style="width: 90%">
                    {% for movie in amovie %}

                        <li>
                            <div class="movie_list_left" style="width: 40%">
                                <a target="_blank" href="#" title="{{ movie.title }}">
                                    <img src="{{ movie.image }}" alt="{{ movie.title }}">
                                    <div class="bottom-cover">
                                        <span class="film-time">{{ movie.duration }}</span>
                                    </div>
                                </a>
                            </div>

                            <div class="movie_list_right" style="width: 60%">
                                <h2>
                                    <a target="_blank" href="" title="{{ movie.title }}">
                                        <span>{{ movie.title }}</span>
                                    </a>
                                </h2>

                                <div class="movie-intro">
                                    {{ movie.title }}
                                </div>
                                <div class="movie-like">
                                    <a href="{% url 'movies:addcollect' movie.id %}"  style="color: black"><span id="movie_like" class="glyphicon glyphicon-heart" ></span></a>
                                    <span></span>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                    <li>
                        <div class="movie_list_left" style="width: 40%">
                            <a target="_blank" href="#" title="超酷一镜到底创意倒放MV《串烧2017》">
                                <img src="https://cs.vmovier.com/Uploads/cover/2017-12-21/5a3b7c046a1d5_cut.jpeg@600w_400h_1e_1c.jpg" alt="超酷一镜到底创意倒放MV《串烧2017》">
                                <div class="bottom-cover">
                                    <span class="film-time">02:48</span>
                                </div>
                            </a>
                        </div>

                        <div class="movie_list_right" style="width: 60%">
                            <h2>
                                <a target="_blank" href="" title="超酷一镜到底创意倒放MV《串烧2017》">
                                    <span>超酷一镜到底创意倒放MV《串烧2017》</span>
                                </a>
                            </h2>

                            <div class="movie-intro">
                                在这个倒叙的世界里，唯有一个人与众不同
                            </div>
                            <div class="movie-like" style="color: red;">
                                <span class="glyphicon glyphicon-heart"></span>
                                <span>199</span>
                            </div>
                        </div>
                    </li>
			    </ul>
                <div class="pagination" style="width: 13%">
                    <ul>
                        {% if amovie.has_previous %}
                            <a href="/movies/logined/{{ user.id }}/?page={{ amovie.previous_page_number }}">上一页</a>
                        {% endif %}
                            <li></li>
                        <span class="current">第 {{ amovie.number }} 页 / 共 {{ amovie.paginator.num_pages }} 页</span>
                        {% if amovie.has_next %}
                            <a href="/movies/logined/{{ user.id }}/?page={{ amovie.next_page_number }}">下一页</a>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <img src="/static/img/5.png" alt="" style="width: 14%;margin-left: 2%">
            <div style="background-color:#ffffff;width: 14%;margin-right: 20%;border: #E5E5E5 solid 2px;float: right;text-align: center;">
                <span style="font-size: 16px;border-left: 4px solid #2689ff;color: #393939;float: left;padding: 5px 0px 5px 18px;margin:10px 0">热门活动</span>
                <ul>
                    <li><img class="img" src="/static/img/1.jpg" alt=""></li>
                    <li><img class="img" src="/static/img/2.jpg" alt=""></li>
                    <li><img class="img" src="/static/img/3.jpg" alt=""></li>
                    <li><img class="img" src="/static/img/4.jpg" alt=""></li>
                    <li><img class="img" src="/static/img/1.jpg" alt=""></li>
                </ul>
            </div>

		</div>

	</body>

</html>

movie/templates/movies/userinfo.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/js/jquery.js"></script>
		<script type="text/javascript" src="/static/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.css" />

		<link rel="stylesheet" type="text/css" href="/static/css/swiper.css" />
		<script type="text/javascript" src="/static/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/css/reset.css" />
		<style type="text/css">
			.form-info {
				border: 1px solid orange;
				margin: 100px auto;
				width: 30%;
				padding: 50px;
			}
			
			.form-info h2 {
				font-size: 2rem;
				margin-bottom: 20px;
			}
			
			.form-info .submit {
				text-align: center;
			}
			
			.form-info img{
				width: 40px;
				height: 40px;
				float: left;
			}
			input[type=file]{
				float: left;
				height: 40px;
				line-height: 40px;
				padding-left: 20px;
			}
		</style>
	</head>

	<body>

		<div class="container-fluid">
			<div class="form-info">

				<h2>信息修改</h2>

				<form action="{% url 'movies:edituser' user.id%}" method="post" enctype="multipart/form-data">
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" class="form-control" id="exampleInputEmail1" placeholder="请输入用户名" name="username" value={{ name }} disabled="disabled">
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">邮箱</label>
						<input type="email" class="form-control" name="email" placeholder="请输入新的邮箱" value={{ email }}>
					</div>
					<div class="form-group clearfix">
						<label for="exampleInputFile">头像</label><br />
						<img class="img-circle" src={{ icons_url }}  />
						<input type="file" id="exampleInputFile" name="uicon">
					</div>
					<div class="submit"><button type="submit" class="btn btn-primary">提交</button></div>

				</form>
			</div>
		</div>

	</body>

</html>